### PR TITLE
fix: move stake button when transfer's locked

### LINKED ISSUE #1769: Transfer locked NAM pushes Stake button left on Overview panel
Image

### PR DESCRIPTION
**Pull request by neocybereth**
Closes #1769

Screenshot 2025-02-27 at 11 52 41 AM

### CODE REVIEW

**Comment by neocybereth** [comment]
@euharrison @pedrorezende Sorry, but I'm unable to add reviewers atm so this is my route :D

**Review by pedrorezende — APPROVED** [review]
Omg THANK YOU hahaha this was driving me crazy lol

File: apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx [hunk 1]
```diff
@@ -85,15 +85,15 @@ const TransparentTokensTable = ({
           {isNam && (
             <ActionButton
               size="xs"
-              className="w-fit mx-auto"
+              className={`w-fit mx-auto ${namTransferLocked ? "-mr-2" : ""}`}
```
Comment (euharrison) [inline apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx:88]: @neocybereth FYI, we have `twMerge` and `clsx` for these cases :)

**Comment by neocybereth** [comment]
Hehe no problem @pedrorezende 🤣
