### PR TITLE
feat: improving bug report info gathering

### LINKED ISSUE #1823: Namadillo: add Debug / Bug Report page
Add a debug page that will help to analyze the user environments and help error reporting

### PR DESCRIPTION
**Pull request by pedrorezende**
This PR opens a new page for bug report, where useful information could be parsed and added directly to bug report form on Github

Closes #1823

### CODE REVIEW

File: apps/namadillo/src/App/Common/BugReport.tsx [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+  const isShieldedSyncComplete = useAtomValue(isShieldedSyncCompleteAtom);
+  const settings = useAtomValue(settingsAtom);
+  const lastShieldedSyncForAccount =
+    account.data?.address ? lastSyncInfo[account.data.address] : "?";
+
+  const yesOrNo = (bool: unknown): string => (!!bool ? "Yes" : "No");
+
+  const sep = "\n------------------";
+  const debugInfo = `## Navigator${sep}
+User Agent: ${navigator.userAgent}</li>
```
Comment (jurevans) [inline apps/namadillo/src/App/Common/BugReport.tsx:38]: This can be removed -> `</li>`

Noticed it in the bug report:
```
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0</li>
```

**Review by jurevans — APPROVED** [review]
This looks great! I just added one small comment
