### PR TITLE
More Governance fixes

### LINKED ISSUE #805: Validate proposal ID from URL query properly
The code to read and validate a proposal ID from the URL params should be put in a utility function somewhere to reduce duplication with ViewJson, ProposalAndVote and SubmitVote. It should also validate properly that we successfully parsed a bigint.

### LINKED ISSUE #811: Opening a proposal page should scroll to the top of the page
When you click to open a proposal from the All Proposals table, the page loads at the bottom instead of scrolling back to the top. The extension already does something like this I think so we can probably reuse that.

### PR DESCRIPTION
**Pull request by emccorson**
### Changed
- Rename Governance overview route to "/" to match Staking
- Make Governance route wildcard to match Staking

### Fixed
- Reuse and fix up proposal ID query param logic
- Add scroll to top behaviour when changing page
- Fix back button not working on Governance page

Fixes #805. Fixes #811.

### CODE REVIEW

File: apps/namadillo/src/hooks/useProposalIdParam.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import { useEffect } from "react";
+import { useNavigate } from "react-router-dom";
+
+import { useSanitizedParams } from "@namada/hooks";
+import GovernanceRoutes from "App/Governance/routes";
+
+const parseProposalId = (asString: string | undefined): bigint | null => {
```
Comment (pedrorezende) [inline apps/namadillo/src/hooks/useProposalIdParam.ts:7]: Nitpick: I would say we should keep BigNumber to make everything standard / compatibility, but we're not making any calculations with that, so I think it's okay. Any thoughts?

File: apps/namadillo/src/App/Governance/Governance.tsx [hunk 2]
```diff
@@ -1,41 +1,26 @@
...
-        <Route path={`${GovernanceRoutes.viewJson()}`} element={<ViewJson />} />
-      </Routes>
-    </main>
-  );
-};
+export const Governance: React.FC = () => (
+  <main className="w-full">
+    <Routes>
+      <Route
+        path={`${GovernanceRoutes.overview()}`}
```
Comment (pedrorezende) [inline apps/namadillo/src/App/Governance/Governance.tsx:12]: We can also make this Route with the property `index`

**Review by pedrorezende — APPROVED** [review]
LGTM, just a few minor comments! o/

File: apps/namadillo/src/hooks/useProposalIdParam.ts (hunk 1 above)
Comment (emccorson) [reply apps/namadillo/src/hooks/useProposalIdParam.ts:7]: I had a further think about this. I think `bigint` is good because it more closely matches the values that are valid proposal IDs (basically `u64` in Rust), whereas `BigNumber` includes more values that are not valid (e.g. non-integers). `bigint` is a bit of pain sometimes to use because it can't be used to index objects or as a React key, but `BigNumber` would have the same problems. If we do need to get a `BigNumber` representation we can always do `BigNumber(someBigInt.toString())`. What do you think? I'll leave it in this PR for now and if you still think it should be changed we can add it later.

File: apps/namadillo/src/App/Governance/Governance.tsx (hunk 2 above)
Comment (emccorson) [reply apps/namadillo/src/App/Governance/Governance.tsx]: `index` didn't seem to work (I think because of a missing trailing `/`), so I just used `"/*"` to match the Staking routes.
