### PR TITLE
feat: fixing ibc shielded gas estimate

### LINKED ISSUE #1486: Namadillo: Gas estimation for IBC MASP is too low
The gas estimation when trying to make an IBC MASP transaction is too low. 

image

We can manually increase that on Keplr as a temporary workaround, but we need to provide a better estimation.

### PR DESCRIPTION
**Pull request by pedrorezende**
First version of estimate gas calculation for IBC shielded transfers. Still requires some minor improvements / tweaks that I'll leave for later PRs, like loading state or refresh button.

I also added 5% more over the estimated gas just to make sure that the transaction will succeed. Maybe we can tweak this percentage using the gas usage selection modal /cc @euharrison

Closes #1486

### CODE REVIEW

File: apps/namadillo/src/utils/index.ts [hunk 1]
```diff
@@ -91,7 +91,9 @@ export const toDisplayAmount = (
   if (!displayUnit) {
     return baseAmount;
   }
-  return baseAmount.shiftedBy(-displayUnit.exponent);
+  return baseAmount
+    .shiftedBy(-displayUnit.exponent)
+    .decimalPlaces(6, BigNumber.ROUND_DOWN);
```
Comment (euharrison) [inline apps/namadillo/src/utils/index.ts:96]: we are using this function to set some value for any transfer, I'm a bit afraid of this imprecision spread to border cases. Shouldn't we apply this only on the visual components on the render phase?

**Review by euharrison — APPROVED** [review]
Nice! 

How about defining a fallback value just in case we can't estimate (like below with ATOM)?

Screenshot 2025-01-17 at 15 40 40

File: apps/namadillo/src/utils/index.ts (hunk 1 above)
Comment (pedrorezende) [reply apps/namadillo/src/utils/index.ts]: Changed. The error on Cosmos is because we can't estimate the gas required using an invalid channel. I've tried to fix that, but we don't have a right way to calculate a fallback for that. Before, the amount of gas used was hardcoded :/
