### PR TITLE
fix: Connect wallet larger click surface 

### LINKED ISSUE #2113: [Namadillo]: Connect wallet larger click surface
On the `Connect Wallet` function, the surface exposed as a button should be large and rectangular encompassing `Keplr` and the space in between `Connect`. Currently, one must hover over the `Connect` text itself only.

Image

### PR DESCRIPTION
**Pull request by neocybereth**
Closes #2113

### CODE REVIEW

File: apps/namadillo/src/App/Transfer/WalletCard.tsx [hunk 1]
```diff
@@ -23,27 +23,32 @@ export const WalletCard = ({
...
+      window.open(getDownloadUrl(), "_blank", "noopener,noreferrer");
+      return;
+    }
+    if (installed && !connected) return onConnect?.();
+    if (installed && connected) return onSelect?.();
+  };
+
   return (
-    <div className="flex justify-between items-center w-full">
+    <div
```
Comment (euharrison) [inline apps/namadillo/src/App/Transfer/WalletCard.tsx:36]: accessibility wise, we need to the tag `<a>` and `<button>`, so user can navigate with tab, right click and open it in a new tab, etc

we can use this pattern if it helps
```tsx
const Component = installed 
  ? ((props) => <a href={getDownloadUrl()} {...props} />) 
  : ((props) => <button onClick={handleClick} {...props} />)
  
<Component ....
```
