### PR TITLE
fix: pending notification not being removed on IBC Withdraw

### LINKED ISSUE #1903: IBC withdraw showing Pending notification indefinitely

### PR DESCRIPTION
**Pull request by neocybereth**
Closes #1903

### CODE REVIEW

**Comment by neocybereth** [comment]
@euharrison @pedrorezende here's the fix for the notification. I'm not sure if this effects anything else downstream so just want to make sure you're aware of the change here.

**Comment by neocybereth** [comment]
Screenshot 2025-04-01 at 1 04 42 PM


@euharrison @pedrorezende here's a temporary fix. Pretty ugly and just extends the existing hack we had, but I think this will have to do for now until we rewrite the `useTransaction` hook

File: apps/namadillo/src/atoms/notifications/functions.ts [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 export const notificationIdSeparator = ";";
 
 export const createNotificationId = (
-  data?: TxProps | TxProps[] | string
+  data?: TxProps | TxProps[] | string | EncodedTxData<TxProps>
 ): string => {
   if (!data) return Date.now().toString();
   if (typeof data === "string") return data;
-
+  if ((data as EncodedTxData<TxProps>).type === "buildIbcTransfer") {
```
Comment (pedrorezende) [inline apps/namadillo/src/atoms/notifications/functions.ts:11]: Wouldn't be better to check first if "type" exists on data? I'm afraid this would throw an error trying to access `type` from an array

Comment (neocybereth) [reply apps/namadillo/src/atoms/notifications/functions.ts]: Good call, I updated that.

**Comment by euharrison** [comment]
While I'm fixing this pending notification from  Claim & Stake https://github.com/anoma/namada-interface/issues/1907 I tested this PR and I'm receiving this error

Screenshot 2025-04-02 at 19 40 26

I think we should avoid as much as possible this pattern of `as Type` because it'll lead to these cases

I don't know yet what is the reason for this, but posting here in case this is useful somehow

**Comment by euharrison** [comment]
In general, I think this `transactionId` as a string is creating a nightmare for us. Maybe it'll be better to handle this as an object, like `createNotificationId(...): { hash: string, innerTxHashes: string[] }` and we can have the freedom to decide how to clean the notifications based on this

**Comment by neocybereth** [comment]
@euharrison @pedrorezende I've updated the `createNotificationId` function to only take in the hash array or hash string type. Now all individual places that call this can handle exactly what they pass in. For most of them it's the transaction hash but for IBC notifications (withdraws in particular) its the innerTxHashes b/c of the API

File: apps/namadillo/src/atoms/notifications/functions.ts [hunk 2]
```diff
@@ -1,21 +1,11 @@
-import { TxProps } from "@namada/types";
-
 export const notificationIdSeparator = ";";
+import { TxProps } from "@namada/types";
 
 export const createNotificationId = (
-  data?: TxProps | TxProps[] | string
+  data?: TxProps["hash"] | TxProps["hash"][]
```
Comment (euharrison) [inline apps/namadillo/src/atoms/notifications/functions.ts:5]: Funny, I was thinking that you will allow passing a bunch of different types and handle them all here returning `string[]` instead of preserving the `data.join(";")`

**Review by euharrison — APPROVED** [review]
Cool! It's working fine on my tests ✅
