### PR TITLE
fix: fixing ibc assets transfer fees

### LINKED ISSUE #1581: Fix transfer error when paying with a different token without balance
My balance is 0.01 OSMO on masp
I tried to pay a transfer that was 0.06 OSMO

The button is hanging on "Submitting..." while we got this sdk error below

Image

### LINKED ISSUE #1621: Add scrollbar on fee modal
We need a scrollbar when selecting a token on the transaction fee modal

Image

### PR DESCRIPTION
**Pull request by pedrorezende**
Making more explicit when we're using display amounts and base denomination amounts. We were having some errors because of that, like in #1581 , also for selecting and displaying fees.

Fixes #1581 
Fixes #1621

### CODE REVIEW

File: apps/namadillo/src/App/Transfer/TransferModule.tsx [hunk 1]
```diff
@@ -144,27 +146,27 @@ export const TransferModule = ({
...
     ) {
       return availableAmount;
     }
 
-    const amountMinusFees = availableAmount.minus(
-      displayGasFee.totalDisplayAmount
-    );
+    const amountMinusFees = availableAmount
+      .minus(displayGasFee.totalDisplayAmount)
+      .decimalPlaces(6);
```
Comment (euharrison) [inline apps/namadillo/src/App/Transfer/TransferModule.tsx:168]: shouldn't we apply this only on render components to be safer?

File: apps/namadillo/src/atoms/fees/atoms.ts [hunk 2]
```diff
@@ -83,8 +83,10 @@ export const gasPriceTableAtom = atomWithQuery<GasPriceTable>((get) => {
         const baseAmount = BigNumber(minDenomAmount);
         return {
           token,
-          // TODO should we run `toDisplayAmount` for all tokens or only NAM?
-          gasPrice: asset ? toDisplayAmount(asset, baseAmount) : baseAmount,
+          gasPrice:
+            asset && isNamadaAsset(asset) ?
```
Comment (euharrison) [inline apps/namadillo/src/atoms/fees/atoms.ts:87]: so is this the answer of the issue!? 🫠

File: apps/namadillo/src/atoms/integrations/services.ts [hunk 3]
```diff
@@ -338,16 +338,20 @@ export const fetchIbcChannelFromRegistry = async (
...
-  return estimatedGas * (1 + additionalPercentage);
+  try {
+    const estimatedGas = await stargateClient.simulate(
+      sourceAddress!,
+      [transferMsg],
+      undefined
+    );
+    return estimatedGas * (1 + additionalPercentage);
+  } catch (error) {
+    throw error;
```
Comment (euharrison) [inline apps/namadillo/src/atoms/integrations/services.ts:355]: I believe this is not necessary anymore

File: apps/namadillo/src/types.ts [hunk 4]
```diff
@@ -40,7 +40,7 @@ export type AddressBalance = Record<Address, BigNumber>;
 
 export type GasConfig = {
   gasLimit: GasLimit;
-  gasPrice: GasPrice;
+  gasPriceInMinDenom: GasPrice;
```
Comment (euharrison) [inline apps/namadillo/src/types.ts:43]: so, could we review this just in case? I can feel your frustration, and I share this as well. What I believe on this specifically case is that it could be the gasPrice on minDenom (for all other tokens), but for Namada this is on displayDenom, or at least this is what I understood on `gasPriceTableAtom`. If this is true, having the `InMinDenom` could lead to more confusion later. So do you think it's reasonable for this case preserve the term `gasPrice` only?

File: apps/namadillo/src/atoms/integrations/services.ts (hunk 3 above)
Comment (pedrorezende) [reply apps/namadillo/src/atoms/integrations/services.ts:355]: I would not risk :P I'll leave that for now until we have everything related to gas estimate 100% fixed

File: apps/namadillo/src/types.ts (hunk 4 above)
Comment (pedrorezende) [reply apps/namadillo/src/types.ts:43]: minDenomAmount on Namada has the same value than the displayAmount :/ this is the biggest cause of confusion. So for Namada it never makes any difference, we'll never pass unam anywhere - I think we only use unam on the CLI to transfer to another chain

File: apps/namadillo/src/atoms/fees/atoms.ts (hunk 2 above)
Comment (pedrorezende) [reply apps/namadillo/src/atoms/fees/atoms.ts:87]: yep :/ we're receiving unam from the indexer, and we use nam everywhere, even on the cli, differently of other tokens

File: apps/namadillo/src/App/Transfer/TransferModule.tsx (hunk 1 above)
Comment (pedrorezende) [reply apps/namadillo/src/App/Transfer/TransferModule.tsx:168]: I think we're fine, since we won't have more than 6 decimal places. In the worst case we'll have a difference of less than 0.000001 for a given amount
