### PR TITLE
fix: robuster way to detect/install keplr (#1267)

### LINKED ISSUE #1267: Namadillo: keplr sometimes is not detected
After trying to transfer assets via IBC transfer panel, sometimes keplr is not detected and the transfer timeline gets stuck in the "Signature" stage. This issue was commonly found in the Discord channel and we should investigate how to replicate this behaviour

### PR DESCRIPTION
**Pull request by zenodeapp**
PR to fix #1267. This makes use of a method described in https://docs.keplr.app/api/#how-to-detect-keplr to detect the Keplr wallet extension.

- This not only checks the `window`-object, but also checks the `document` state before it eventually decides whether Keplr is installed or not.
- Added an install method which opens the keplr download page in a _blank tab.
- Added the `install()` and `get()` functions to the `WalletConnector`-interface as this is likely going to become common among other integrations. But unsure about this, so tell me if this needs to go.
- `getSigner` needed to become an async function due to this detection method.

In my testing I didn't get problems with detecting Keplr anymore, but please double check if it's resolved. I'll also open another PR with a simpler approach, but I don't think that one is as robust as this method (#1283).

ZEN

### CODE REVIEW

File: apps/namadillo/src/integrations/Keplr.ts [hunk 1]
```diff
@@ -8,21 +9,55 @@ import { WalletConnector } from "./types";
 import { basicConvertToKeplrChain } from "./utils";
 
 type Signer = OfflineAminoSigner & OfflineDirectSigner;
-const keplr = (window as KeplrWindow).keplr!;
 
 export class KeplrWalletManager implements WalletConnector {
+  install(): void {
+    console.warn("Keplr is not available. Redirecting to the Keplr download page...");
+    window.open("https://www.keplr.app/get", "_blank");
+  }
```
Comment (jurevans) [inline apps/namadillo/src/integrations/Keplr.ts:17]: I think this is good! Though we may want to invoke `install()` from outside of the integration (for example, if `get()` doesn't return Keplr, we could display a `Download` button, which in turn invokes `install()`, instead of calling it automatically). I wanted to see what @pedrorezende thought of this too, as we've been chatting about how to handle that scenario for Keplr. Perhaps we can keep this method (`install()`), but invoke it outside of `get()`?

Comment (zenodeapp) [reply apps/namadillo/src/integrations/Keplr.ts:17]: That's an idea indeed! So commenting out the part where it automatically calls install, but keep the install method so it's callable? 

It would also be an idea to have like an `isInstalled()` method to quickly see whether it is around or not and base the button on this boolean value.

I'm not behind the pc atm, but I could remove the part where it auto calls install inside of the get!

Comment (jurevans) [reply apps/namadillo/src/integrations/Keplr.ts:17]: Yeah, I think for now, just take out `if(!keplr) this.install();` so that it's not automatically called. We need to figure out exactly how to handle the Download button still on our end, and we can certainly address that in another PR!

Comment (pedrorezende) [reply apps/namadillo/src/integrations/Keplr.ts:17]: I agree with @jurevans , later today I can hook this `install` method somewhere in order to download Keplr after clicking on a button to do so. Thank you very much for this PR @zenodeapp !

**Review by pedrorezende — APPROVED** [review]
LGTM! Thank you very much!

**Comment by pedrorezende** [comment]
Fixes #1267

**Comment by zenodeapp** [comment]
One final remark, it might become necessary to create an `isInstalled()` method for the button logic, due to the non-null assertion in the `get()` function, like:

```js
async isInstalled(): Promise<boolean> {
    const keplr = await _get();
    return keplr !== undefined;
}
```
