### PR TITLE
Namadillo: fixing amount conversion and timeline stage

### LINKED ISSUE #1288: Namadaillo Decimal Precision issue
I am trying to tx 2000 NAM from account with 98K NAM and i got this err 
`The balance of the source tnam1qpj9aye7zd of token tnam1q9gr66cvu4hrzm0sd5 is lower than the amount to be transferred. Amount to transfer is 2000000000.000000 and the balance is 98021.612521.`

### PR DESCRIPTION
**Pull request by pedrorezende**
This fixes #1288 and also make some tweaks on error handling and timeline stages. This is one more step forward on Transfer page development.

### CODE REVIEW

File: apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx [hunk 1]
```diff
@@ -106,8 +102,23 @@ export const NamadaTransfer: React.FC = () => {
       title: "Transfer transaction failed",
       description: "",
     }),
+    onSigned: () => {
+      setCurrentStep(1);
+    },
   };
 
+  useTransactionEventListListener(
```
Comment (euharrison) [inline apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx:110]: great idea 🧠

**Review by euharrison — APPROVED** [review]

**Review by jurevans — APPROVED** [review]
LGTM!
