### PR TITLE
bug: select active account and remove fiat currency

### LINKED ISSUE #630: Interface - updates & bugs
Adding relatively small changes to the interface here:

- [ ] Remove conversion to USD/EUR/etc. from interface, display only token balance
  - Remove or disable `coins` slice
  - Remove settings page where currency is selected
  - Remove total balance summing
- [ ] Transfer page is still not setting a selected account when there is only one account, which can result in validation failing for the `amount` field

### PR DESCRIPTION
**Pull request by mateuszjasiuk**
Resolves #630 

To test the "invalid ~~balance~~ amount" bug. First import account without balance and then one with balance.

### CODE REVIEW

**Review by jurevans — APPROVED** [review]
LGTM!

File: apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx [hunk 1]
```diff
@@ -135,6 +107,7 @@ const DerivedAccounts = (): JSX.Element => {
           .map((account) => {
             const { alias, address, isShielded } = account;
             const balance = balances[address];
+            const nativeBalance = typeof balance === "undefined" ? "-" : (balance?.[symbol]?.toString() || "0");
```
Comment (emccorson) [inline apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx:110]: The optional chaining on `balance` should be unneeded here.

File: apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx [hunk 2]
```diff
@@ -151,7 +124,11 @@ const DerivedAccounts = (): JSX.Element => {
                       )}
                     </DerivedAccountType>
                   </DerivedAccountInfo>
-                  <FiatBalanceDisplay balance={balance} />
+                  <div className="flex items-center">
+                    <span className="text-white">
+                      {Tokens[symbol].symbol} {nativeBalance?.toString()}
```
Comment (emccorson) [inline apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx:129]: I think you can remove `?.toString()` here since `nativeBalance` is of type `string`.

**Review by emccorson — APPROVED** [review]
Code looks good and works well! I left a couple of minor comments.

File: apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx (hunk 1 above)
Comment (mateuszjasiuk) [reply apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx:110]: I think balance was undefined sometimes when I was testing it, but I will double check

Comment (mateuszjasiuk) [reply apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx:110]: Ah right I'm checking that 😅
